### ISSUE TITLE
Current TODO tasks

### ISSUE THREAD

**Issue by jovany-wang** [jovany-wang/dousi#2]
- [x] Encapsulate asio::socket as a class with `AsnycRead()`, `AsyncWrite`. #6 
- [ ] Refine APIs.
- [x] Use spdlog instead of mack log. #23
- [x] Add more basic and complex tests.
- [x] Add basic benchmark.
- [ ] Support exporting installed headers and libs.
- [x] Use io threads. #38
- [x] master uses stream lib #22
- [ ] Refactor service instance performing process with one by one remote call.
- [ ] Use condition variable instead of while true getting object.
